version: '3'
services:
  backend:
    image: todobackend
    restart: always
    ports: 
      - 3001:3001
  frontend:
    image: todofrontend
    restart: always
    ports: 
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=backend
    depends_on:
      - backend
  todotests:
    image: todotests
    restart: on-failure
    environment:
      - FRONT_HOST=frontend
    depends_on:
      - frontend
      - backend